const subcategoryFields = {
  Mobile: [
    { label: "Title", type: "text", name: "title" },
    { label: "Brand", type: "text", name: "brand" },
    {
      label: "Price",
      min: 0,
      type: "number",
      name: "price",
    },
    {
      label: "Condition",
      type: "select",
      name: "condition",
      options: ["New", "Gently Used", "Heavily Used"],
    },
    { label: "Color", type: "text", name: "color" },
    {
      label: "Warranty",
      type: "select",
      name: "warranty",
      options: ["Yes", "No"],
    },
    { label: "Location", type: "text", name: "location" },
    { label: "Additional Info", type: "textarea", name: "additionalInfo" },
  ],
  Headphones: [
    { label: "Title", type: "text", name: "title" },
    { label: "Brand", type: "text", name: "brand" },
    { label: "Price", type: "number", name: "price" },
    {
      label: "Wireless",
      type: "select",
      name: "wireless",
      options: ["Yes", "No"],
    },
    {
      label: "Noise Cancellation",
      type: "select",
      name: "noiseCancellation",
      options: ["Yes", "No"],
    },
    { label: "Color", type: "text", name: "color" },
    {
      label: "Warranty",
      type: "select",
      name: "warranty",
      options: ["Yes", "No"],
    },
    { label: "Location", type: "text", name: "location" },
    { label: "Additional Info", type: "textarea", name: "additionalInfo" },
  ],
  Charger: [
    { label: "Title", type: "text", name: "title" },
    { label: "Brand", type: "text", name: "brand" },
    { label: "Price", type: "number", name: "price" },
    {
      label: "Fast Charging Support",
      type: "select",
      name: "fastCharging",
      options: ["Yes", "No"],
    },
    {
      label: "Type",
      type: "select",
      name: "type",
      options: ["USB-C", "Micro-USB", "Lightning"],
    },
    {
      label: "Condition",
      type: "select",
      name: "condition",
      options: ["New", "Gently Used", "Heavily Used"],
    },
    { label: "Location", type: "text", name: "location" },
    { label: "Additional Info", type: "textarea", name: "additionalInfo" },
  ],
  Laptop: [
    { label: "Title", type: "text", name: "title" },
    { label: "Brand", type: "text", name: "brand" },
    { label: "Processor", type: "text", name: "processor" },
    { label: "RAM Size", type: "text", name: "ramSize" },
    { label: "Storage Type", type: "text", name: "storageType" },
    { label: "Price", type: "number", name: "price" },
    {
      label: "Condition",
      type: "select",
      name: "condition",
      options: ["New", "Gently Used", "Heavily Used"],
    },
    { label: "Color", type: "text", name: "color" },
    {
      label: "Warranty",
      type: "select",
      name: "warranty",
      options: ["Yes", "No"],
    },
    { label: "Location", type: "text", name: "location" },
    { label: "Additional Info", type: "textarea", name: "additionalInfo" },
  ],
  "Mountain Bike": [
    { label: "Title", type: "text", name: "title" },
    { label: "Brand", type: "text", name: "brand" },
    { label: "Price", type: "number", name: "price" },
    { label: "Frame Material", type: "text", name: "frameMaterial" },
    { label: "Gear Count", type: "number", name: "gearCount" },
    { label: "Suspension Type", type: "text", name: "suspensionType" },
    {
      label: "Condition",
      type: "select",
      name: "condition",
      options: ["New", "Gently Used", "Heavily Used"],
    },
    { label: "Color", type: "text", name: "color" },
    { label: "Location", type: "text", name: "location" },
    { label: "Additional Info", type: "textarea", name: "additionalInfo" },
  ],
  "Road Bike": [
    { label: "Title", type: "text", name: "title" },
    { label: "Brand", type: "text", name: "brand" },
    { label: "Price", type: "number", name: "price" },
    { label: "Frame Material", type: "text", name: "frameMaterial" },
    { label: "Gear Count", type: "number", name: "gearCount" },
    { label: "Tire Type", type: "text", name: "tireType" },
    {
      label: "Condition",
      type: "select",
      name: "condition",
      options: ["New", "Gently Used", "Heavily Used"],
    },
    { label: "Color", type: "text", name: "color" },
    { label: "Location", type: "text", name: "location" },
    { label: "Additional Info", type: "textarea", name: "additionalInfo" },
  ],
  "Hybrid Bike": [
    { label: "Title", type: "text", name: "title" },
    { label: "Brand", type: "text", name: "brand" },
    { label: "Price", type: "number", name: "price" },
    { label: "Frame Material", type: "text", name: "frameMaterial" },
    { label: "Gear Count", type: "number", name: "gearCount" },
    { label: "Brake Type", type: "text", name: "brakeType" },
    {
      label: "Condition",
      type: "select",
      name: "condition",
      options: ["New", "Gently Used", "Heavily Used"],
    },
    { label: "Color", type: "text", name: "color" },
    { label: "Location", type: "text", name: "location" },
    { label: "Additional Info", type: "textarea", name: "additionalInfo" },
  ],
  Fiction: [
    { label: "Title", type: "text", name: "title" },
    { label: "Author", type: "text", name: "author" },
    { label: "Price", type: "number", name: "price" },
    { label: "Language", type: "text", name: "language" },
    { label: "Genre", type: "text", name: "genre" },
    {
      label: "Condition",
      type: "select",
      name: "condition",
      options: ["New", "Gently Used", "Heavily Used"],
    },
    { label: "Publication Year", type: "number", name: "publicationYear" },
    { label: "Location", type: "text", name: "location" },
    { label: "Additional Info", type: "textarea", name: "additionalInfo" },
  ],
  "Non-fiction": [
    { label: "Title", type: "text", name: "title" },
    { label: "Author", type: "text", name: "author" },
    { label: "Price", type: "number", name: "price" },
    { label: "Subject", type: "text", name: "subject" },
    {
      label: "Condition",
      type: "select",
      name: "condition",
      options: ["New", "Gently Used", "Heavily Used"],
    },
    { label: "Publication Year", type: "number", name: "publicationYear" },
    { label: "Location", type: "text", name: "location" },
    { label: "Additional Info", type: "textarea", name: "additionalInfo" },
  ],
  Educational: [
    { label: "Title", type: "text", name: "title" },
    { label: "Author", type: "text", name: "author" },
    { label: "Price", type: "number", name: "price" },
    { label: "Subject", type: "text", name: "subject" },
    { label: "Grade Level", type: "text", name: "gradeLevel" },
    {
      label: "Condition",
      type: "select",
      name: "condition",
      options: ["New", "Gently Used", "Heavily Used"],
    },
    { label: "Publication Year", type: "number", name: "publicationYear" },
    { label: "Location", type: "text", name: "location" },
    { label: "Additional Info", type: "textarea", name: "additionalInfo" },
  ],
  Comics: [
    { label: "Title", type: "text", name: "title" },
    { label: "Series", type: "text", name: "series" },
    { label: "Volume", type: "number", name: "volume" },
    { label: "Language", type: "text", name: "language" },
    { label: "Price", type: "number", name: "price" },
    {
      label: "Condition",
      type: "select",
      name: "condition",
      options: ["New", "Gently Used", "Heavily Used"],
    },
    { label: "Publication Year", type: "number", name: "publicationYear" },
    { label: "Location", type: "text", name: "location" },
    { label: "Additional Info", type: "textarea", name: "additionalInfo" },
  ],
  Shirt: [
    { label: "Title", type: "text", name: "title" },
    { label: "Brand", type: "text", name: "brand" },
    { label: "Size", type: "text", name: "size" },
    { label: "Material", type: "text", name: "material" },
    { label: "Pattern", type: "text", name: "pattern" },
    { label: "Price", type: "number", name: "price" },
    {
      label: "Condition",
      type: "select",
      name: "condition",
      options: ["New", "Gently Used", "Heavily Used"],
    },
    { label: "Color", type: "text", name: "color" },
    {
      label: "Gender",
      type: "select",
      name: "gender",
      options: ["Men", "Women", "Unisex"],
    },
    { label: "Location", type: "text", name: "location" },
    { label: "Additional Info", type: "textarea", name: "additionalInfo" },
  ],
  Pants: [
    { label: "Title", type: "text", name: "title" },
    { label: "Brand", type: "text", name: "brand" },
    { label: "Size", type: "text", name: "size" },
    { label: "Material", type: "text", name: "material" },
    { label: "Fit Type", type: "text", name: "fitType" },
    { label: "Price", type: "number", name: "price" },
    {
      label: "Condition",
      type: "select",
      name: "condition",
      options: ["New", "Gently Used", "Heavily Used"],
    },
    { label: "Color", type: "text", name: "color" },
    {
      label: "Gender",
      type: "select",
      name: "gender",
      options: ["Men", "Women", "Unisex"],
    },
    { label: "Location", type: "text", name: "location" },
    { label: "Additional Info", type: "textarea", name: "additionalInfo" },
  ],
  Dress: [
    { label: "Title", type: "text", name: "title" },
    { label: "Brand", type: "text", name: "brand" },
    { label: "Size", type: "text", name: "size" },
    { label: "Material", type: "text", name: "material" },
    { label: "Length", type: "text", name: "length" },
    { label: "Price", type: "number", name: "price" },
    {
      label: "Condition",
      type: "select",
      name: "condition",
      options: ["New", "Gently Used", "Heavily Used"],
    },
    { label: "Color", type: "text", name: "color" },
    {
      label: "Gender",
      type: "select",
      name: "gender",
      options: ["Women"],
    },
    { label: "Location", type: "text", name: "location" },
    { label: "Additional Info", type: "textarea", name: "additionalInfo" },
  ],
  Jacket: [
    { label: "Title", type: "text", name: "title" },
    { label: "Brand", type: "text", name: "brand" },
    { label: "Size", type: "text", name: "size" },
    { label: "Material", type: "text", name: "material" },
    { label: "Price", type: "number", name: "price" },
    {
      label: "Condition",
      type: "select",
      name: "condition",
      options: ["New", "Gently Used", "Heavily Used"],
    },
    { label: "Color", type: "text", name: "color" },
    {
      label: "Gender",
      type: "select",
      name: "gender",
      options: ["Men", "Women", "Unisex"],
    },
    { label: "Location", type: "text", name: "location" },
    { label: "Additional Info", type: "textarea", name: "additionalInfo" },
  ],
  Table: [
    { label: "Title", type: "text", name: "title" },
    { label: "Material", type: "text", name: "material" },
    { label: "Shape", type: "text", name: "shape" },
    { label: "Dimensions", type: "text", name: "dimensions" },
    { label: "Price", type: "number", name: "price" },
    {
      label: "Condition",
      type: "select",
      name: "condition",
      options: ["New", "Gently Used", "Heavily Used"],
    },
    { label: "Color", type: "text", name: "color" },
    { label: "Location", type: "text", name: "location" },
    { label: "Additional Info", type: "textarea", name: "additionalInfo" },
  ],
  Chair: [
    { label: "Title", type: "text", name: "title" },
    { label: "Material", type: "text", name: "material" },
    { label: "Type", type: "text", name: "type" },
    { label: "Price", type: "number", name: "price" },
    {
      label: "Condition",
      type: "select",
      name: "condition",
      options: ["New", "Gently Used", "Heavily Used"],
    },
    { label: "Color", type: "text", name: "color" },
    { label: "Location", type: "text", name: "location" },
    { label: "Additional Info", type: "textarea", name: "additionalInfo" },
  ],
  Sofa: [
    { label: "Title", type: "text", name: "title" },
    { label: "Material", type: "text", name: "material" },
    { label: "Seating Capacity", type: "number", name: "seatingCapacity" },
    { label: "Price", type: "number", name: "price" },
    {
      label: "Condition",
      type: "select",
      name: "condition",
      options: ["New", "Gently Used", "Heavily Used"],
    },
    { label: "Color", type: "text", name: "color" },
    { label: "Location", type: "text", name: "location" },
    { label: "Additional Info", type: "textarea", name: "additionalInfo" },
  ],
  Bed: [
    { label: "Title", type: "text", name: "title" },
    { label: "Material", type: "text", name: "material" },
    { label: "Size", type: "text", name: "size" },
    { label: "Price", type: "number", name: "price" },
    {
      label: "Condition",
      type: "select",
      name: "condition",
      options: ["New", "Gently Used", "Heavily Used"],
    },
    { label: "Color", type: "text", name: "color" },
    { label: "Location", type: "text", name: "location" },
    { label: "Additional Info", type: "textarea", name: "additionalInfo" },
  ],
  Miscellaneous: [
    { label: "Title", type: "text", name: "title" },
    { label: "Description", type: "textarea", name: "description" },
    { label: "Price", type: "number", name: "price" },
    {
      label: "Condition",
      type: "select",
      name: "condition",
      options: ["New", "Gently Used", "Heavily Used"],
    },
    { label: "Color", type: "text", name: "color" },
    { label: "Location", type: "text", name: "location" },
    { label: "Additional Info", type: "textarea", name: "additionalInfo" },
  ],
};

export default subcategoryFields;
